### ISSUE TITLE
Orbiter does not send updated position information

### ISSUE THREAD

**Issue by hcjetter** [huddlelamp/huddle-orbiter#1]
At this moment, when I use Orbiter to simulate device movements for an app using HuddleCanvas, the canvas position is not updated on the client device - even if I use the mouse to drag or rotate the device in Orbiter for many seconds or almost a minute. However, other messages from Orbiter are received and executed by the client immediately, e.g. "switch red on/off", "show marker on/off". 

In fact, the only way I get a Huddle Canvas application to update its rendering from Orbiter is to manually switch to "show marker" and then back again. After this, there happens one single update when I drag the tablet in Orbiter with the mouse, but after this there is again no update anymore.

This could of course also be a bug on the client-side, e.g. in the Huddle Canvas API or Huddle Client APi.

**Comment by raedle** [comment]
This is a bug in the huddle:canvas API. The canvas updates only if physical device motion (accelerometer) is detected.
